### ISSUE TITLE
Could not run on Windows

### ISSUE THREAD

**Issue by redmanmale** [ralphwetzel/theonionbox#25]
I'm new to python so excuse me for some parts of this issue as you might think it's pretty obvious.

- There's no info about supported Python version, so I tried both consequentially.
- I tried to use setup.py, build and install commands. As I can see, install command create .egg file, but I couldn't figure out how to run it.
- I tried to run directly theonionbox.py from build folder.
  - After first run it gave me a list with missing modules, which I installed than.
  - Python3 gave me this error: 

```python
Traceback (most recent call last):
  File "theonionbox.py", line 81, in <module>
    from tob.scheduler import Scheduler
ImportError: No module named 'tob'
```

  - I also tried it with Python2.7, installed all those modules and got this error:
```python
  File "theonionbox.py", line 81, in <module>
    from tob.scheduler import Scheduler
ImportError: No module named tob.scheduler
```

This errors are due some problem with Apscheduler module, but I couldn't figure out how to fix it.

**Env**
Windows 7 x64, python 3.4, python 2.7.

**Comment by redmanmale** [comment]
After reboot it seems to work, though.
