### ISSUE TITLE
Build breaks with python-3.6: UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 542: ordinal not in range(128)

### ISSUE THREAD

**Issue by yurivict** [ralphwetzel/theonionbox#52]
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "setup.py", line 361, in <module>
    long_description=open('docs/description.rst').read(),
  File "/usr/local/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 542: ordinal not in range(128)
```

**Comment by ralphwetzel** [comment]
Well. I don't know, what you're trying to achieve - yet it does not break on my build system.
Could you please provide further details?

**Comment by yurivict** [comment]
> I don't know, what you're trying to achieve

It breaks in the FreeBSD port https://www.freshports.org/security/theonionbox when ```USES=python``` is replaced with ```USES=python:3.4+```.

I've seen this error with other projects. Usually, truncating the ```README``` file helped.

**Comment by ralphwetzel** [comment]
> Usually, truncating the `README` file helped.

Truncating anything is no option.

Could you please provide a link to the procedure you're following to create the port - to allow me to replicate this issue?

**Comment by yurivict** [comment]
```
(cd /usr/ports/security/theonionbox/work/theonionbox-4.2.1; /usr/bin/env XDG_DATA_HOME=/usr/ports/security/theonionbox/work  XDG_CONFIG_HOME=/usr/ports/security/theonionbox/work  HOME=/usr/ports/security/theonionbox/work PATH=/usr/ports/security/theonionbox/work/.bin:.:/home/yuri/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin NO_PIE=yes MK_DEBUG_FILES=no MK_KERNEL_SYMBOLS=no SHELL=/bin/sh NO_LINT=YES LDSHARED="cc -shared" PYTHONDONTWRITEBYTECODE= PYTHONOPTIMIZE= PREFIX=/usr/local  LOCALBASE=/usr/local  CC="cc" CFLAGS="-O2 -pipe -fno-omit-frame-pointer  -fstack-protector -fno-strict-aliasing"  CPP="cpp" CPPFLAGS="-fno-omit-frame-pointer"  LDFLAGS=" -fstack-protector" LIBS=""  CXX="c++" CXXFLAGS="-O2 -pipe -fno-omit-frame-pointer -fstack-protector -fno-strict-aliasing -fno-omit-frame-pointer "  MANPREFIX="/usr/local" BSD_INSTALL_PROGRAM="install  -s -m 555"  BSD_INSTALL_LIB="install  -s -m 0644"  BSD_INSTALL_SCRIPT="install  -m 555"  BSD_INSTALL_DATA="install  -m 0644"  BSD_INSTALL_MAN="install  -m 444" /usr/local/bin/python3.6 -c  "import sys; import setuptools;  __file__='setup.py'; sys.argv[0]='setup.py';  exec(compile(open(__file__, 'rb').read().replace(b'\\r\\n', b'\\n'), __file__, 'exec'))" config )
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "setup.py", line 361, in <module>
    long_description=open('docs/description.rst').read(),
  File "/usr/local/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 542: ordinal not in range(128)
```

**Comment by ralphwetzel** [comment]
Could you please replace your `setup.py` with the one from the referenced commit & re-run the procedure?
