### ISSUE TITLE
install new on debian jessie

### ISSUE THREAD

**Issue by 011248163264** [ralphwetzel/theonionbox#62]
------------------------------------------------------------
/home/onion/theonionbox/bin/pip run on Sun Dec  2 00:37:56 2018
Downloading/unpacking theonionbox
  Getting page https://pypi.python.org/simple/theonionbox/
  URLs to search for versions for theonionbox:
  * https://pypi.python.org/simple/theonionbox/
  Analyzing links from page https://pypi.org/simple/theonionbox/
    Found link https://files.pythonhosted.org/packages/eb/ae/ce88ad44eb6132ef0ff66a12440e2a55da1f9ba0f3121c0bf767e0b87d47/theonionbox-4.1.0.tar.gz#sha256=850c587b2c3211c3f53dc4424e3da2a9cd9449663f0c762eb0c50e74a9b800d2 (from https://pypi.org/simple/theonionbox/), version: 4.1.0
    Found link https://files.pythonhosted.org/packages/e8/da/380f756dcf8fb94bcb9eb48921502cf323bd3b6de4fd933963a5317afaeb/theonionbox-4.1.1.tar.gz#sha256=2d85fc8a9d7b3dc524876715564b81d439b0efa394682b033a32f022461a857f (from https://pypi.org/simple/theonionbox/), version: 4.1.1
    Found link https://files.pythonhosted.org/packages/7d/12/cbec79c18cdbd84d593c26d2bcf908d407d670efdbca37a07c99afb4a900/theonionbox-4.1.2.tar.gz#sha256=9dd60081b52b69745adc39f5b21235384e028d25039aba1b88f0b4ac926a9587 (from https://pypi.org/simple/theonionbox/), version: 4.1.2
    Found link https://files.pythonhosted.org/packages/a0/65/a4cb119b059af7314cb069a7818f09282076ee8b67eadc813c7b091ad8fe/theonionbox-4.1.3.tar.gz#sha256=e3886e176768f0b6bcff0d966b6a3318f581f924506942c617a3d18125374b6e (from https://pypi.org/simple/theonionbox/), version: 4.1.3
    Found link https://files.pythonhosted.org/packages/e8/f4/07c1e7602dc8e86a3e18a62c231ceed3fd87a4a3ec00336f54f77914b377/theonionbox-4.2.tar.gz#sha256=13068be1008c8e981fe7aa044316beb889d3e930a3731b549fdc137fe1680a10 (from https://pypi.org/simple/theonionbox/), version: 4.2
    Found link https://files.pythonhosted.org/packages/30/92/b3cb97120e0537cece919c454080505c23c00033cafb27228bd0ec593877/theonionbox-4.2.1.tar.gz#sha256=834a6e15d7074a74331866b2d05b18435ede0e5fd061def9f3e6ff7c9e2b481a (from https://pypi.org/simple/theonionbox/), version: 4.2.1
    Found link https://files.pythonhosted.org/packages/f6/90/bab164846bc3f59c2b05f9c15bcf6221d228a5b0a6517673d035be5db228/theonionbox-4.3.0.tar.gz#sha256=30b614fa8a3c9145e9e70fa479eaa775a9ea82911aa6615de1a1fad2b6a821a6 (from https://pypi.org/simple/theonionbox/), version: 4.3.0
  Using version 4.3.0 (newest of versions: 4.3.0, 4.2.1, 4.2, 4.1.3, 4.1.2, 4.1.1, 4.1.0)
  Downloading from URL https://files.pythonhosted.org/packages/f6/90/bab164846bc3f59c2b05f9c15bcf6221d228a5b0a6517673d035be5db228/theonionbox-4.3.0.tar.gz#sha256=30b614fa8a3c9145e9e70fa479eaa775a9ea82911aa6615de1a1fad2b6a821a6 (from https://pypi.org/simple/theonionbox/)
  Running setup.py (path:/home/onion/theonionbox/build/theonionbox/setup.py) egg_info for package theonionbox
    /usr/lib/python3.4/distutils/dist.py:260: UserWarning: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
    error in theonionbox setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers
    Complete output from command python setup.py egg_info:
    /usr/lib/python3.4/distutils/dist.py:260: UserWarning: Unknown distribution option: 'long_description_content_type'

  warnings.warn(msg)

error in theonionbox setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers

----------------------------------------
Cleaning up...
  Removing temporary dir /home/onion/theonionbox/build...
Command python setup.py egg_info failed with error code 1 in /home/onion/theonionbox/build/theonionbox
Exception information:
Traceback (most recent call last):
  File "/home/onion/theonionbox/lib/python3.4/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/home/onion/theonionbox/lib/python3.4/site-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/home/onion/theonionbox/lib/python3.4/site-packages/pip/req.py", line 1230, in prepare_files
    req_to_install.run_egg_info()
  File "/home/onion/theonionbox/lib/python3.4/site-packages/pip/req.py", line 326, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/home/onion/theonionbox/lib/python3.4/site-packages/pip/util.py", line 715, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command python setup.py egg_info failed with error code 1 in /home/onion/theonionbox/build/theonionbox

**Comment by 011248163264** [comment]
the same with python2.7

onion@zb:~/theonionbox$ source bin/activate
(theonionbox)onion@zb:~/theonionbox$ pip install theonionbox
Downloading/unpacking theonionbox
  Downloading theonionbox-4.3.0.tar.gz (13.1MB): 13.1MB downloaded
  Running setup.py (path:/home/onion/theonionbox/build/theonionbox/setup.py) egg_info for package theonionbox
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
    error in theonionbox setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers
    Complete output from command python setup.py egg_info:
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'long_description_content_type'

  warnings.warn(msg)

error in theonionbox setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /home/onion/theonionbox/build/theonionbox
Storing debug log for failure in /home/onion/.pip/pip.log
(theonionbox)onion@zb:~/theonionbox$

**Comment by ralphwetzel** [comment]
Educated guess, based on googling: This is related to you using an outdated version of `setuptools`.
Try to `pip install -U setuptools` and rerun the installation procedure.
